/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useMemo } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useAppStore } from "../../store/useAppStore";

// Constants for Bass Geometry (from BassNeck.tsx)
const TOTAL_FRETS = 24;
const STRINGS = 4;

// ✅ FINAL CALIBRATED POSITIONS (MANUAL MEASUREMENT)
// Index = Fret Number (0 to 20)
const FRET_POSITIONS = [
  -1.46, // Fret 0 (Nut)
  -4.15, // Fret 1
  -6.55, // Fret 2 (Estimated/Interpolated)
  -8.94, // Fret 3
  -11.15, // Fret 4
  -13.21, // Fret 5
  -15.15, // Fret 6
  -16.97, // Fret 7
  -18.74, // Fret 8
  -20.34, // Fret 9
  -21.9, // Fret 10
  -23.34, // Fret 11
  -24.7, // Fret 12
  -26.02, // Fret 13
  -27.25, // Fret 14
  -28.38, // Fret 15
  -29.5, // Fret 16
  -30.52, // Fret 17
  -31.45, // Fret 18
  -32.4, // Fret 19
  -33.27, // Fret 20 (Last fret)
];

export function BassModel(props: JSX.IntrinsicElements["group"]) {
  const gltf = useGLTF("/bass_guitar_white.glb");
  const scene = gltf.scene;
  const { trackData, currentTime } = useAppStore();

  // Global Calibration Constants
  const markerPos = [-0.1, 13.9, -29.0];
  const markerRot = [0, 3.14, -1.6];
  const markerScale = 1.43;

  // Simplified function: No math, just lookup
  const getFretZ = (fret: number): number => {
    // If transcription sends a note higher than 20 (e.g. 21-24),
    // clamp it to 20 so it doesn't crash or float in void.
    const safeFret = Math.min(Math.max(fret, 0), 20);
    return FRET_POSITIONS[safeFret];
  };

  // Simplified String Y Logic
  const STRING_SPACING = 0.6;
  const getStringY = (stringIndex: number, fretIndex: number) => {
    // Center the strings around Y=0
    // We ignore fretIndex for spacing now as we use constant spacing
    const centerOffset = (STRING_SPACING * (STRINGS - 1)) / 2;
    // Invert the direction so index 0 (E) is lowest (negative Y)
    return -centerOffset + stringIndex * STRING_SPACING;
  };

  // Pro Studio String Colors
  // E (0) = Burnt Orange, A (1) = Gold, D (2) = Steel Blue, G (3) = Teal
  const STRING_COLORS = ["#D35400", "#F1C40F", "#5DADE2", "#1ABC9C"];

  return (
    <group {...props} dispose={null}>
      <primitive object={scene} />

      {/* Markers Group with calibrated transform */}
      <group
        position={markerPos as [number, number, number]}
        rotation={markerRot as [number, number, number]}
        scale={markerScale}
      >
        {/* STRING HIGHLIGHTS - Light up active strings (ONE per string) */}
        {(() => {
          const SYNC_OFFSET = 0.2;
          // Group active notes by string to avoid duplicate highlights
          const activeStrings = new Set<number>();
          const activeNotesByString = new Map<number, any>();

          trackData?.notes.forEach((note) => {
            const isActive =
              currentTime >= note.time + SYNC_OFFSET &&
              currentTime < note.time + note.duration + SYNC_OFFSET;
            if (isActive) {
              activeStrings.add(note.string);
              // Keep the first active note for positioning
              if (!activeNotesByString.has(note.string)) {
                activeNotesByString.set(note.string, note);
              }
            }
          });

          return Array.from(activeStrings).map((stringIndex) => {
            const note = activeNotesByString.get(stringIndex)!;
            const y = getStringY(stringIndex, note.fret);
            const z = getFretZ(note.fret);
            const stringColor = STRING_COLORS[stringIndex];

            return (
              <group
                key={`string-highlight-${stringIndex}`}
                position={[0, y, z]}
              >
                {/* Shorter, localized highlight around the active fret */}
                <boxGeometry args={[0.08, 0.06, 4]} />
                <meshBasicMaterial
                  color={stringColor}
                  transparent
                  opacity={0.5}
                />
                {/* Long string glow effect (visual tube) */}
                <mesh rotation={[Math.PI / 2, 0, 0]} position={[0, 0, 0]}>
                  <cylinderGeometry args={[0.02, 0.02, 8, 8]} />
                  <meshBasicMaterial
                    color={stringColor}
                    transparent
                    opacity={0.6}
                  />
                </mesh>
              </group>
            );
          });
        })()}

        {/* ACTIVE & ANTICIPATED NOTES */}
        {trackData?.notes.map((note) => {
          const SYNC_OFFSET = 0.2; // Compensate for audio latency
          const isActive =
            currentTime >= note.time + SYNC_OFFSET &&
            currentTime < note.time + note.duration + SYNC_OFFSET;

          // Upcoming notes - show 3s before (better anticipation with centered playhead)
          const ANTICIPATION_WINDOW = 3.0; // Show notes 3 seconds ahead
          const isAnticipated =
            currentTime >= note.time - ANTICIPATION_WINDOW + SYNC_OFFSET &&
            currentTime < note.time + SYNC_OFFSET;

          if (!isActive && !isAnticipated) return null;

          const y = getStringY(note.string, note.fret);
          const z = getFretZ(note.fret);
          const stringColor = STRING_COLORS[note.string];

          // COLOR SCHEME:
          // Upcoming (Anticipated) = White ghost (prepare your finger)
          // Active = String Color (PLUCK NOW!)
          const markerColor = isActive ? stringColor : "#FFFFFF";
          const markerEmissive = isActive ? stringColor : "#CCCCCC";
          const markerOpacity = isActive ? 1.0 : 0.5; // Increased from 0.3 for better visibility
          const markerSize = isActive ? 0.35 : 0.2; // Increased from 0.12 for better visibility
          const emissiveIntensity = isActive ? 2.0 : 0.8; // Elegant glow (reduced from 4.0)

          return (
            <group key={note.id} position={[0, y, z]}>
              {/* Main Marker Sphere */}
              <mesh>
                <sphereGeometry args={[markerSize, 32, 32]} />
                <meshStandardMaterial
                  color={markerColor}
                  emissive={markerEmissive}
                  emissiveIntensity={emissiveIntensity}
                  transparent
                  opacity={markerOpacity}
                />
              </mesh>

              {/* Fret number label - only show when active */}
              {isActive && (
                <Text
                  position={[0, 0.7, 0]}
                  fontSize={0.6}
                  color="#FFFFFF"
                  anchorX="center"
                  anchorY="middle"
                  outlineWidth={0.1}
                  outlineColor="#000000"
                  fontWeight="bold"
                >
                  {note.fret}
                </Text>
              )}

              {/* Pulsing ring for active notes - BIGGER and BRIGHTER */}
              {isActive && (
                <mesh rotation={[-Math.PI / 2, 0, 0]}>
                  <ringGeometry args={[0.4, 0.55, 32]} />
                  <meshBasicMaterial
                    color={stringColor}
                    transparent
                    opacity={0.8}
                    side={THREE.DoubleSide}
                  />
                </mesh>
              )}

              {/* Outer glow ring for active notes */}
              {isActive && (
                <mesh rotation={[-Math.PI / 2, 0, 0]}>
                  <ringGeometry args={[0.55, 0.7, 32]} />
                  <meshBasicMaterial
                    color={stringColor}
                    transparent
                    opacity={0.4}
                    side={THREE.DoubleSide}
                  />
                </mesh>
              )}
            </group>
          );
        })}

        {/* Subtle fret marker dots (always visible) */}
        {[3, 5, 7, 9, 12, 15, 17, 19].map((fret) => (
          <mesh
            key={`dot-${fret}`}
            position={[
              0,
              0,
              getFretZ(fret) + (getFretZ(fret - 1) - getFretZ(fret)) / 2,
            ]}
          >
            <sphereGeometry args={[0.08, 16, 16]} />
            <meshBasicMaterial color="#888888" opacity={0.4} transparent />
          </mesh>
        ))}
      </group>
    </group>
  );
}

useGLTF.preload("/bass_guitar_white.glb");
